#
# included when using profile 'vagrantbox'
#
zmon:
  oauth2:
    sso:
      client-id: 344c9a90fc697fe6662a #vagrantbox
      client-secret: a2bbb03a29f6737af04c77f2d88e8f8199ff179b #vagrantbox
  signup:
    github:
      # Specify users who are authorized to log in
      # Empty list allows all users to log in
      allowed-users: []
      # Specify organizations who are authorized to log in
      allowed-orgas: []
  authorities:
    simple:
      admins: []
      users: []
  teams:
    simple:
      teams:
        jbellmann:
          - firstTeam
          - secondTeam
          - thirdTeam
    rest:
      get-alert-results:
        allowed-filters:
          - application

