spring:
  application:
    name: ZMON

  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    pool:
      max-active: 8
      max-idle: 8
      min-idle: 0
      max-wait: -1

  datasource:
    driverClassName: org.postgresql.Driver
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/local_zmon_db}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    initSQL: "SET search_path to zzm_api${zzm_api_version}, public;"

  thymeleaf:
    cache: false
    mode: LEGACYHTML5

server:
    port: 8443
    ssl:
        key-store: classpath:keystore.p12
        key-store-type: PKCS12
        key-store-password: mypassword
        key-alias: localhost

zmon:
    cloud:
      checkid: 9
    eventlog:
        url: http://localhost:8081/
    kairosdb:
        enabled: true
        url: http://localhost:38083/
    grafana-min-interval: 60

    redis:
      write:
        host: ${REDIS_WRITE_HOST:${REDIS_HOST:localhost}}
        port: ${REDIS_WRITE_PORT:${REDIS_PORT:6379}}
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1
