zmon:
  zauth:
    oauth2-access-token-url: ${OAUTH2_ACCESS_TOKEN_URL}
  oauth2:
    sso:
      credentials-directory-path: ${CREDENTIALS_DIR}

tokens:
  enableMock: false
  access-token-uri: ${OAUTH2_ACCESS_TOKEN_URL}
  credentials-directory: ${CREDENTIALS_DIR}
  token-configuration-list:
    - token-id: kairosdb
      scopes: uid
    - token-id: team-service
      scopes: uid
    - token-id: user-service
      scopes: uid
